/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dk.lystrup.randomtd.ui;

import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author rolf
 */
public class MainWindow extends javax.swing.JFrame {

    private GamePanel game;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();

        game = GamePanel.instance();
        
        this.setTitle("Random TD");
        this.setSize(1024, 768);
        this.getContentPane().add(game);
        this.setVisible(true);
        
        Executors.newSingleThreadScheduledExecutor().schedule(() -> {
            MainWindow.this.repaint();
        }, 1000 / 60, TimeUnit.MILLISECONDS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
